[build]
target-dir = "target"

[registries.crates-io]
protocol = "sparse"

[target.x86_64-pc-windows-msvc]

rustflags = ["-C", "target-cpu=x86-64", "-C", "target-feature=-avx,-avx2,-avx512f", "-C", "opt-level=2"]

[target.x86_64-unknown-linux-gnu]

rustflags = ["-C", "target-cpu=x86-64", "-C", "target-feature=-avx,-avx2,-avx512f", "-C", "opt-level=2"]

[target.x86_64-apple-darwin]

rustflags = ["-C", "target-cpu=x86-64", "-C", "target-feature=-avx,-avx2,-avx512f", "-C", "opt-level=2"]
